[tool.poetry]
name = "sorting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
streamlit = "*"
plotly = "*"
pandas = "*"
numpy = "*"
matplotlib = "*"
